In [1]:
import tensorflow as tf

In [2]:
physical_devices = tf.config.experimental.list_physical_devices('GPU')
if len(physical_devices) > 0:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
    print("Done")
else:
    print("no gpu")

Done


In [3]:
#dependencies

import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import cv2
import warnings
from core.yolov4 import filter_boxes
import core.utils as utils
import time
from tensorflow.python.saved_model import tag_constants
warnings.filterwarnings('ignore') 


In [8]:
#loading the saved model
PATH_TO_SAVED_MODEL="C:/Users/nitis/tensorflow-yolov4-tflite-master/checkpoints/custom-608"
print('Loading model...', end='')
# Load saved model and build the detection function
loaded_model=tf.saved_model.load(PATH_TO_SAVED_MODEL, tags=[tag_constants.SERVING])
print("Done")

Loading model...Done


In [9]:
infer = loaded_model.signatures["serving_default"]

In [10]:
# label_map = {1:"up",2:"down",3:"left",4:"right"}

In [11]:
# import os
# os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'

In [12]:
# #getting frames from webcam through opencv2
vid = cv2.VideoCapture(0) 
vid.set(cv2.CAP_PROP_FRAME_WIDTH, 608)
vid.set(cv2.CAP_PROP_FRAME_HEIGHT, 608)
while(True): 
    # Capture the video frame 
    # by frame  
    start_time = time.time()
    ret, frame = vid.read() 
    resized = cv2.resize(frame, (608,608), interpolation = cv2.INTER_AREA)
    # Display the resulting frame 
    input_tensor=tf.convert_to_tensor(resized)
    input_tensor = tf.cast(input_tensor,dtype=tf.float32)
    #print(type(input_tensor))
    # The model expects a batch of images, so add an axis with `tf.newaxis`.
    input_tensor=input_tensor[tf.newaxis, ...]
    # input_tensor = np.expand_dims(image_np, 0) 
    detections=infer(input_tensor)
    for key,value in detections.items():
        boxes = value[:, :, 0:4]
        pred_conf = value[:, :, 4:]
        print(boxes)

    #print(resized_frame.shape)
        boxes, scores, classes, valid_detections = tf.image.combined_non_max_suppression(
            boxes=tf.reshape(boxes, (tf.shape(boxes)[0], -1, 1, 4)),
            scores=tf.reshape(
                pred_conf, (tf.shape(pred_conf)[0], -1, tf.shape(pred_conf)[-1])),
            max_output_size_per_class=50,
            max_total_size=50,
            iou_threshold=0.45,
            score_threshold=0.25
        )
    pred_bbox = [boxes.numpy(), scores.numpy(), classes.numpy(), valid_detections.numpy()]
#     print(pred_bbox)
    image = utils.draw_bbox(frame, pred_bbox)
    fps = 1.0 / (time.time() - start_time)
    print("FPS: %.2f" % fps)
    result = np.asarray(image)
    cv2.namedWindow("result", cv2.WINDOW_AUTOSIZE)
    cv2.imshow('result', result) 
    # the 'q' button is set as the 
    # quitting button you may use any 
    # desired button of your choice 
    if cv2.waitKey(1) & 0xFF == ord('q'): 
        break
# After the loop release the cap object 

vid.release() 
# Destroy all the windows 
cv2.destroyAllWindows() 

tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 0.18
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 10.10
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 10.00
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 9.80
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 10.40
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 10.75
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.69
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.51
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 7.98
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.15
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 7.91
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 7.92
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.97
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.54
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 7.24
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.21
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.06
tf.Tensor([], shape=(1, 0, 4), dtype=float32

tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.06
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 7.83
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 7.69
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.56
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.39
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 7.29
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.13
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 7.34
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.11
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 9.04
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 7.78
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.70
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.69
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 7.63
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.26
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 7.31
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FPS: 8.13
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
FP

In [13]:
print(boxes)
print(scores)
print(classes)

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 50, 4), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [14]:
print(boxes)
print(pred_conf)

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 50, 4), dtype=float32)
tf.Tensor([], shape=(1, 0, 4), dtype=float32)
